// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using yotm.Insfrastructure.Data;

#nullable disable

namespace yotm.Insfrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251120064340_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("yotm.Core.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(8766),
                            FullName = "Sistem Yöneticisi",
                            PasswordHash = "$2a$11$zHZ6pJM.2BmwiIKA40/b7.AYxDMOGnOIdsSXXgQ/qTrumaE9SUO76",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("yotm.Core.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Faculty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Instructor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CEN1003",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9417),
                            Department = "Bilgisayar Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Prof. Dr. Ahmet Yılmaz",
                            IsActive = true,
                            Name = "Computer Programming I",
                            Quota = 30
                        },
                        new
                        {
                            Id = 2,
                            Code = "CEN2001",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9419),
                            Department = "Bilgisayar Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Doç. Dr. Ayşe Demir",
                            IsActive = true,
                            Name = "Data Structures",
                            Quota = 35
                        },
                        new
                        {
                            Id = 3,
                            Code = "CEN2005",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9420),
                            Department = "Bilgisayar Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Dr. Öğr. Üyesi Mehmet Kaya",
                            IsActive = true,
                            Name = "Object Oriented Programming",
                            Quota = 30
                        },
                        new
                        {
                            Id = 4,
                            Code = "CEN2002",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9423),
                            Department = "Bilgisayar Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Prof. Dr. Zeynep Akar",
                            IsActive = true,
                            Name = "Analysis of Algorithms",
                            Quota = 25
                        },
                        new
                        {
                            Id = 5,
                            Code = "CEN3001",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9434),
                            Department = "Bilgisayar Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Doç. Dr. Can Öztürk",
                            IsActive = true,
                            Name = "Advanced Computer Programming",
                            Quota = 28
                        },
                        new
                        {
                            Id = 6,
                            Code = "CEN3007",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9436),
                            Department = "Bilgisayar Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Dr. Öğr. Üyesi Elif Şahin",
                            IsActive = true,
                            Name = "Database Systems I",
                            Quota = 32
                        },
                        new
                        {
                            Id = 7,
                            Code = "CEN3002",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9438),
                            Department = "Bilgisayar Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Prof. Dr. Ali Yıldırım",
                            IsActive = true,
                            Name = "Software Engineering",
                            Quota = 30
                        },
                        new
                        {
                            Id = 8,
                            Code = "CEN3004",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9440),
                            Department = "Bilgisayar Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Doç. Dr. Fatma Arslan",
                            IsActive = true,
                            Name = "Operating Systems",
                            Quota = 30
                        },
                        new
                        {
                            Id = 9,
                            Code = "CEN3006",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9442),
                            Department = "Bilgisayar Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Dr. Öğr. Üyesi Burak Tekin",
                            IsActive = true,
                            Name = "Computer Networks",
                            Quota = 28
                        },
                        new
                        {
                            Id = 10,
                            Code = "MTH3004",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9444),
                            Department = "Bilgisayar Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Prof. Dr. Selin Yıldız",
                            IsActive = true,
                            Name = "Numerical Analysis",
                            Quota = 25
                        },
                        new
                        {
                            Id = 11,
                            Code = "SEN1001",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9446),
                            Department = "Yazılım Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Prof. Dr. Emre Çelik",
                            IsActive = true,
                            Name = "Introduction to Software Engineering",
                            Quota = 35
                        },
                        new
                        {
                            Id = 12,
                            Code = "SEN2001",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9588),
                            Department = "Yazılım Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Doç. Dr. Deniz Koç",
                            IsActive = true,
                            Name = "Object Oriented Programming I",
                            Quota = 30
                        },
                        new
                        {
                            Id = 13,
                            Code = "SEN2002",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9591),
                            Department = "Yazılım Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Dr. Öğr. Üyesi Ceren Aydın",
                            IsActive = true,
                            Name = "Database Design and Management",
                            Quota = 32
                        },
                        new
                        {
                            Id = 14,
                            Code = "SEN3001",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9592),
                            Department = "Yazılım Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Doç. Dr. Kerem Polat",
                            IsActive = true,
                            Name = "Visual Programming",
                            Quota = 28
                        },
                        new
                        {
                            Id = 15,
                            Code = "SEN3003",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9594),
                            Department = "Yazılım Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Prof. Dr. Seda Güneş",
                            IsActive = true,
                            Name = "Software Design and Analysis",
                            Quota = 25
                        },
                        new
                        {
                            Id = 16,
                            Code = "SEN3002",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9596),
                            Department = "Yazılım Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Dr. Öğr. Üyesi Cem Karaca",
                            IsActive = true,
                            Name = "Internet & Web Programming",
                            Quota = 35
                        },
                        new
                        {
                            Id = 17,
                            Code = "SEN3004",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9598),
                            Department = "Yazılım Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Prof. Dr. Leyla Toprak",
                            IsActive = true,
                            Name = "Software Architecture",
                            Quota = 25
                        },
                        new
                        {
                            Id = 18,
                            Code = "SEN4001",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9599),
                            Department = "Yazılım Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Doç. Dr. Mert Erdoğan",
                            IsActive = true,
                            Name = "Software Testing",
                            Quota = 30
                        },
                        new
                        {
                            Id = 19,
                            Code = "SEN4010",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9601),
                            Department = "Yazılım Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Prof. Dr. Tuğba Akman",
                            IsActive = true,
                            Name = "Artificial Intelligence",
                            Quota = 28
                        },
                        new
                        {
                            Id = 20,
                            Code = "SEN4002",
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 39, 958, DateTimeKind.Local).AddTicks(9603),
                            Department = "Yazılım Mühendisliği",
                            Faculty = "Mühendislik Fakültesi",
                            Instructor = "Dr. Öğr. Üyesi Berk Yılmaz",
                            IsActive = true,
                            Name = "Software Verification and Validation",
                            Quota = 22
                        });
                });

            modelBuilder.Entity("yotm.Core.Entities.CourseApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProcessedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("CoursesApplication");
                });

            modelBuilder.Entity("yotm.Core.Entities.OtpCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber", "Code", "IsUsed");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("yotm.Core.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StudentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("yotm.Core.Entities.CourseApplication", b =>
                {
                    b.HasOne("yotm.Core.Entities.Course", "Course")
                        .WithMany("Applications")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("yotm.Core.Entities.Student", "Student")
                        .WithMany("Applications")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("yotm.Core.Entities.Course", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("yotm.Core.Entities.Student", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
